/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeofencesRouteImport } from './routes/geofences'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VehiclesNewRouteImport } from './routes/vehicles/new'
import { Route as VehiclesIdRouteImport } from './routes/vehicles/$id'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminFleetRouteImport } from './routes/admin/fleet'
import { Route as VehiclesIdEditRouteImport } from './routes/vehicles/$id.edit'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeofencesRoute = GeofencesRouteImport.update({
  id: '/geofences',
  path: '/geofences',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesNewRoute = VehiclesNewRouteImport.update({
  id: '/vehicles/new',
  path: '/vehicles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/admin/fleet',
  path: '/admin/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdEditRoute = VehiclesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => VehiclesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/geofences': typeof GeofencesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/vehicles/$id': typeof VehiclesIdRouteWithChildren
  '/vehicles/new': typeof VehiclesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/vehicles/$id/edit': typeof VehiclesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/geofences': typeof GeofencesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/vehicles/$id': typeof VehiclesIdRouteWithChildren
  '/vehicles/new': typeof VehiclesNewRoute
  '/admin': typeof AdminIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/vehicles/$id/edit': typeof VehiclesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/geofences': typeof GeofencesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/users': typeof AdminUsersRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/vehicles/$id': typeof VehiclesIdRouteWithChildren
  '/vehicles/new': typeof VehiclesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/vehicles/$id/edit': typeof VehiclesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/geofences'
    | '/login'
    | '/register'
    | '/reports'
    | '/admin/fleet'
    | '/admin/users'
    | '/profile/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/admin/'
    | '/vehicles/'
    | '/vehicles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/geofences'
    | '/login'
    | '/register'
    | '/reports'
    | '/admin/fleet'
    | '/admin/users'
    | '/profile/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/admin'
    | '/vehicles'
    | '/vehicles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/geofences'
    | '/login'
    | '/register'
    | '/reports'
    | '/admin/fleet'
    | '/admin/users'
    | '/profile/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/settings/profile'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/admin/'
    | '/vehicles/'
    | '/vehicles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  GeofencesRoute: typeof GeofencesRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ProfileIdRoute: typeof ProfileIdRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  VehiclesIdRoute: typeof VehiclesIdRouteWithChildren
  VehiclesNewRoute: typeof VehiclesNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geofences': {
      id: '/geofences'
      path: '/geofences'
      fullPath: '/geofences'
      preLoaderRoute: typeof GeofencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/new': {
      id: '/vehicles/new'
      path: '/vehicles/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof VehiclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/admin/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$id/edit': {
      id: '/vehicles/$id/edit'
      path: '/edit'
      fullPath: '/vehicles/$id/edit'
      preLoaderRoute: typeof VehiclesIdEditRouteImport
      parentRoute: typeof VehiclesIdRoute
    }
  }
}

interface VehiclesIdRouteChildren {
  VehiclesIdEditRoute: typeof VehiclesIdEditRoute
}

const VehiclesIdRouteChildren: VehiclesIdRouteChildren = {
  VehiclesIdEditRoute: VehiclesIdEditRoute,
}

const VehiclesIdRouteWithChildren = VehiclesIdRoute._addFileChildren(
  VehiclesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  GeofencesRoute: GeofencesRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminUsersRoute: AdminUsersRoute,
  ProfileIdRoute: ProfileIdRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  VehiclesIdRoute: VehiclesIdRouteWithChildren,
  VehiclesNewRoute: VehiclesNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
